apiVersion: v1
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 4dd006301f669d044c60fd579bb24fb08133f26f
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "image_based_video_search.labels" . | nindent 4 }}
    katenary.v3/component: broker
  name: '{{ include "image_based_video_search.fullname" . }}-broker'
