apiVersion: v1
data:
  ETCD_USE_EMBED: "true"
  ETCD_DATA_DIR: "/var/libe/milvus/etcd"
  ETCD_CONFIG_PATH: "/milvus/configs/custom/embedEtcd.yaml"
  COMMON_STORAGETYPE: "local"
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 4dd006301f669d044c60fd579bb24fb08133f26f
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "image_based_video_search.labels" . | nindent 4 }}
    katenary.v3/component: milvusdb
  name: '{{ include "image_based_video_search.fullname" . }}-milvusdb-env'
---
apiVersion: v1
data:
  embedEtcd.yaml: |
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://0.0.0.0:2379
    quota-backend-bytes: 4294967296
    auto-compaction-mode: revision
    auto-compaction-retention: '1000'
  user.yaml: |
    # Extra config to override default milvus.yaml
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 4dd006301f669d044c60fd579bb24fb08133f26f
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "image_based_video_search.labels" . | nindent 4 }}
    katenary.v3/component: milvusdb
  name: '{{ include "image_based_video_search.fullname" . }}-milvusdb-config'
