apiVersion: v1
kind: Service
metadata:
  annotations:
    katenary.v3/compose-hash: 4dd006301f669d044c60fd579bb24fb08133f26f
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "image_based_video_search.labels" . | nindent 4 }}
    katenary.v3/component: milvusdb
  name: '{{ include "image_based_video_search.fullname" . }}-milvusdb'
spec:
  ports:
  - name: milvusdb-19530
    port: 19530
    protocol: TCP
    targetPort: 19530
  - name: milvusdb-9091
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: milvusdb-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    {{- include "image_based_video_search.selectorLabels" . | nindent 4 }}
    katenary.v3/component: milvusdb
