# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: ibvs-app
version: 1.0.0
description: "Image-Based Video Search Sample Application"

helmRegistry: "docker-hub"
chartName: "intel/image-based-video-search"
chartVersion: "1.0.0"

profiles:
  - name: "default"
    valuesFileName: "ibvs-values.yaml"
    parameterTemplates:
      - name: httpProxy
        displayName: "Http proxy"
        type: string
        default: ""
      - name: httpsProxy
        displayName: "Https proxy"
        type: string
        default: ""
      - name: noProxy
        displayName: "No proxy"
        type: string
        default: "localhost,127.0.0.1"
